---
title: "Spectral imaging for evaluation of spatial distributions of leaf photosynthetic light use efficiency" 
author: "Keach Murakami, Yasuomi Ibaraki (Graduate School of Sicences and Technology for Innovation, Yamaguchi University)"
output:
  html_document:
    theme: NULL
    keep_md: TRUE
---

# Abstract

Evaluating intra-plant spatial distributions of photosynthetic light use efficiency (LUE; photosynthetic rate per photosynthetic photon flux density (PPFD)) may help improving light environmental control in horticultural systems (e.g. interlighting in greenhouses).
Photochemical reflectance index (PRI), a parameter calculated from leaf spectral reflectances at two wavebands, represents a positive correlation with LUE (Garbulsky et al. 2011) and thus may be applicable for LUE monitoring.
However, most previous studies on PRI imaging have focused on the application to large-scale and/or long-term monitoring (e.g. satellite-based phenology).
The aim of this study is to examine the applicability of PRI imaging for small-scale (i.e. leaves to whole-plant) and short-term (i.e. hourly to daily) LUE monitoring.
Dark-adapted leaves of 2-week-old cucumber seedlings were subjected to the following PRI imaging.
Time-lapse images of the leaves and a reflectance standard were captured using two CMOS cameras with band-pass filters and PRI values of binned pixels were calculated according to Gamon et al. (1997).
Time-courses of PRI after the commencement of irradiation at several PPFDs were measured and compared with those of the photochemical yield of photosystem II (<i>Y</i><sub>II</sub>, also known as &Phi;<sub>II</sub>), which is highly correlated with LUE (e.g. Genty et al. 1989).
Irrespective of the PPFDs, <i>Y</i><sub>II</sub> dropped sharply after the commencement of irradiation and then recovered gradually to the stable values.
The PRI followed the decrease phases with time delays irrespective of the PPFDs while the recovery phases were only observed under low PPFD conditions.
The differences between PRI values at dark- and light-adapted states represented a considerable correlation with the steady state <i>Y</i><sub>II</sub>.
These results suggest that PRI imaging may be applicable for detecting a drop in LUE and estimating spatial distributions of steady-state LUEs in horticultural systems.
Up-to-date results including estimated spatial distributions of leaf photosynthetic rates by spectral imaging will be shared.

```{r, echo = FALSE}
TITLE <- "Spectral imaging for evaluation of spatial distributions of leaf photosynthetic light use efficiency" 
AUTHOR <- "Keach Murakami, Yasuomi Ibaraki (Graduate School of Sicences and Technology for Innovation, Yamaguchi University)"

word_count <-
  list(TITLE, AUTHOR) %>%
  map_int(~ stringr::str_split(., pattern = " ") %>% .[[1]] %>% length) %>%
  sum

cat(paste0("words in title & author: ", word_count, "\n"))
wordcountaddin::text_stats("abstract.Rmd")
```